name: Build and deploy Python app to Azure Web App - servicioPeliculas

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and activate virtual environment
        working-directory: ./backend/movies_service
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: ./backend/movies_service
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        working-directory: ./backend/movies_service
        run: |
          source venv/bin/activate
          zip -r ../../release.zip . -x "venv/bin/*" -x "venv/include/*" -x "venv/share/*" -x "venv/pyvenv.cfg"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: List files before zipping
        run: ls -la

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27FE43B035B9417F97D110AC37AEC420 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_497FD18E210F4F388A82036C2F0488EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A8980EB44EE2416898863878C12B30C9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'servicioPeliculas'
          slot-name: 'Production'
          package: .
          startup-command: 'gunicorn app:app --bind 0.0.0.0:$PORT'
